CKPT_FREQ: 20
PRINT_FREQ: 50
MODEL:
  META_ARCHITECTURE: "vinai_panoptic_deeplab"
  BN_MOMENTUM: 0.01
  BACKBONE:
    META: "hrnet"
    NAME: "hrnet32"
    DILATION: (False, False, False)
    PRETRAINED: False
  DECODER:
    IN_CHANNELS: 256
    FEATURE_KEY: "res5"
    DECODER_CHANNELS: 256
    ATROUS_RATES: (3, 6, 9)
  PANOPTIC_DEEPLAB:
    LOW_LEVEL_CHANNELS: (128, 64, 32)
    LOW_LEVEL_KEY: ["res4", "res3", "res2"]
    LOW_LEVEL_CHANNELS_PROJECT: (96, 48, 24)
    INSTANCE:
      ENABLE: True
      LOW_LEVEL_CHANNELS_PROJECT: (64, 32, 16)
      DECODER_CHANNELS: 96
      HEAD_CHANNELS: 32
      ASPP_CHANNELS: 256
      NUM_CLASSES: (1, 2)
      CLASS_KEY: ["center", "offset"]
      ORACLE_SEMANTIC: True
      SEMANTIC_EMBED_CHANNELS: 64
    FREEZE_MODULE: ''
    SEMANTIC:
      PRETRAINED: '/raid/tungnd13/ml4annotation_models/pretrained_weights_210722/sem_seg_cityscapes_finetune_210107.pth'
      IGNORE_HEAD: True
  WEIGHTS: '/home/tungnd13/chuonghm/ml4annotation_ins_seg/outputs/vinai_panoptic_exp2/final_state.pth'
DATASET:
  DATASET: "vinai_panoptic"
  ROOT: "/home/tungnd13/chuonghm/ml4annotation_ins_seg/datasets/210803_2k_auditted"
  TRAIN_FILE: 'train_tuning.txt'
  TEST_FILE: 'val_tuning.txt'
  CROP_SIZE: (1208, 1920)
  RESCALE_SIZE: (512, 1024)
  NUM_CLASSES: 17
  MIRROR: True
  MIN_SCALE: 0.8
  MAX_SCALE: 1.2
  SCALE_STEP_SIZE: 0.02
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  SMALL_INSTANCE_AREA: 4096
  SMALL_INSTANCE_WEIGHT: 3
DATALOADER:
  NUM_WORKERS: 8
  SAMPLER_TRAIN: 'RandomSampler'
SOLVER:
  BASE_LR: 0.000003
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY_BIAS: 0.0
  OPTIMIZER: "adam"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  WARMUP_ITERS: 0
LOSS:
  SEMANTIC:
    NAME: "ohem"
    WEIGHT: 1.0
    THRESHOLD: 0.9
    MIN_KEPT: 50000
  CENTER:
    NAME: "mse"
    WEIGHT: 200.0
  OFFSET:
    NAME: "l1"
    WEIGHT: 0.01
TRAIN:
  RESUME: True
  IMS_PER_BATCH: 3
  MAX_ITER: 10
DEBUG:
  DEBUG: True
  DEBUG_FREQ: 1
TEST:
  MODEL_FILE: ''
  EVAL_INSTANCE: True
  EVAL_PANOPTIC: True
  INSTANCE_COCO_EVAL: "/home/tungnd13/chuonghm/ml4annotation_ins_seg/datasets/210803_2k_auditted/annotations/instance_val.pkl"
  PANOP_JSON: "/home/tungnd13/chuonghm/ml4annotation_ins_seg/datasets/210803_2k_auditted/annotations/panoptic_val.json"
  ORACLE_FOREGROUND: False
  ORACLE_SEMANTIC: False
  CROP_SIZE: (1208, 1920)
  RESCALE_SIZE: (512, 1024)
  DEBUG: False
POST_PROCESSING:
  CENTER_THRESHOLD: 0.1
  NMS_KERNEL: 7
  TOP_K_INSTANCE: 200
  STUFF_AREA: 2048
OUTPUT_DIR: "/home/tungnd13/chuonghm/ml4annotation_ins_seg/outputs/vinai_panoptic_exp3_instance_ce_weight_tuning"
# OUTPUT_DIR: './outputs/debug'
GPUS: (0, )
WORKERS: 1
