CKPT_FREQ: 20
PRINT_FREQ: 20
MODEL:
  META_ARCHITECTURE: "vinai_panoptic_deeplab"
  BN_MOMENTUM: 0.01
  BACKBONE:
    META: "hrnet"
    NAME: "hrnet32"
    DILATION: (False, False, False)
    PRETRAINED: False
  DECODER:
    IN_CHANNELS: 256
    FEATURE_KEY: "res5"
    DECODER_CHANNELS: 256
    ATROUS_RATES: (3, 6, 9)
  PANOPTIC_DEEPLAB:
    LOW_LEVEL_CHANNELS: (128, 64, 32)
    LOW_LEVEL_KEY: ["res4", "res3", "res2"]
    LOW_LEVEL_CHANNELS_PROJECT: (96, 48, 24)
    INSTANCE:
      ENABLE: False
      LOW_LEVEL_CHANNELS_PROJECT: (64, 32, 16)
      DECODER_CHANNELS: 96
      HEAD_CHANNELS: 32
      ASPP_CHANNELS: 256
      NUM_CLASSES: (1, 2)
      CLASS_KEY: ["center", "offset"]
      ORACLE_SEMANTIC: True
      SEMANTIC_EMBED_CHANNELS: 64
    FREEZE_MODULE: 'instance'
    SEMANTIC:
      PRETRAINED: '/raid/tungnd13/ml4annotation_models/pretrained_weights_210722/sem_seg_cityscapes_finetune_210107.pth'
      IGNORE_HEAD: True
  WEIGHTS: 'outputs/vinai_panoptic_stage1_semantic_40k/iter_13.pth'
DATASET:
  DATASET: "vinai_panoptic"
  ROOT: "/home/tungnd13/tuanpa36/audit_20210713_mapping"
  TRAIN_FILE: 'train_audit.txt'
  TEST_FILE: 'val_audit.txt'
  CROP_SIZE: (1208, 1920)
  RESCALE_SIZE: (512, 1024)
  NUM_CLASSES: 17
  MIRROR: True
  MIN_SCALE: 0.8
  MAX_SCALE: 1.2
  SCALE_STEP_SIZE: 0.02
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  SMALL_INSTANCE_AREA: 4096
  SMALL_INSTANCE_WEIGHT: 3
DATALOADER:
  NUM_WORKERS: 10
  SAMPLER_TRAIN: 'DistributedSampler'
SOLVER:
  BASE_LR: 0.00002
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY_BIAS: 0.0
  OPTIMIZER: "adam"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  WARMUP_ITERS: 0
LOSS:
  SEMANTIC:
    NAME: "ohem"
    WEIGHT: 1.0
    THRESHOLD: 0.9
    MIN_KEPT: 50000
  CENTER:
    NAME: "mse"
    WEIGHT: 200.0
  OFFSET:
    NAME: "l1"
    WEIGHT: 0.01
TRAIN:
  RESUME: True
  IMS_PER_BATCH: 25
  # IMS_PER_BATCH: 2
  MAX_ITER: 5
DEBUG:
  DEBUG: False
  DEBUG_FREQ: 1
  TARGET_KEYS: ('semantic', )
  OUTPUT_KEYS: ('semantic', )
TEST:
  EVAL_INSTANCE: False
  EVAL_PANOPTIC: False
  ORACLE_FOREGROUND: False
  ORACLE_SEMANTIC: False
  CROP_SIZE: (1208, 1920)
  RESCALE_SIZE: (512, 1024)
  DEBUG: False
POST_PROCESSING:
  CENTER_THRESHOLD: 0.1
  NMS_KERNEL: 7
  TOP_K_INSTANCE: 200
  STUFF_AREA: 2048
OUTPUT_DIR: "./outputs/vinai_panoptic_stage2_semantic_7k"
# OUTPUT_DIR: './outputs/debug'
GPUS: (0, 1, 2, 3, 4)
WORKERS: 1
